language: rust
cache: cargo
rust:
  - stable
allow_failures:
  - nightly
os:
  - linux
before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi
script:
  - cargo update --verbose
  - cargo build --all --all-features --verbose
  - cargo test --verbose